## Deliverable 2. Create a Customer Travel Destinations Map.

In [13]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [14]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dubrovka,RU,53.6907,33.5071,15.78,96,100,4.74,snow
1,1,Saint-Philippe,RE,-21.3585,55.7679,72.99,72,95,12.93,light rain
2,2,Cape Town,ZA,-33.9258,18.4232,68.41,76,0,7.00,clear sky
3,3,Chuy,UY,-33.6971,-53.4616,75.67,93,100,6.55,moderate rain
4,4,Elmira,US,42.0898,-76.8077,23.00,58,20,6.91,few clouds
5,5,Mount Isa,AU,-20.7333,139.5000,82.17,83,40,11.50,scattered clouds
6,6,Jamestown,US,42.0970,-79.2353,18.72,85,100,8.05,overcast clouds
7,7,Ust-Kulom,RU,53.6907,33.5071,15.78,96,100,4.74,snow
8,8,Wangqing,CN,43.3218,129.7634,8.94,90,39,1.88,scattered clouds
9,9,Dikson,RU,53.6907,33.5071,15.78,96,100,4.74,snow

In [15]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip? "))
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 10
What is your desired maximum temperature for your trip? 40

In [16]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
cities_preferred_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) & (city_data_df["Max Temp"] <= max_temp)]
cities_preferred_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dubrovka,RU,53.6907,33.5071,15.78,96,100,4.74,snow
4,4,Elmira,US,42.0898,-76.8077,23.00,58,20,6.91,few clouds
6,6,Jamestown,US,42.0970,-79.2353,18.72,85,100,8.05,overcast clouds
7,7,Ust-Kulom,RU,53.6907,33.5071,15.78,96,100,4.74,snow
9,9,Dikson,RU,53.6907,33.5071,15.78,96,100,4.74,snow
12,12,Lavrentiya,RU,53.6907,33.5071,15.78,96,100,4.74,snow
13,13,Andenes,NO,69.3143,16.1194,28.38,93,100,11.50,overcast clouds
21,21,Belushya Guba,RU,53.6907,33.5071,15.78,96,100,4.74,snow
27,27,Tyukalinsk,RU,53.6907,33.5071,15.78,96,100,4.74,snow
28,28,Grindavik,IS,63.8424,-22.4338,30.67,86,75,3.44,broken clouds

In [17]:
# 4a. Determine if there are any empty rows.
print(len(cities_preferred_df))
cities_preferred_df.count()

197

City_ID                197
City                   197
Country                197
Lat                    197
Lng                    197
Max Temp               197
Humidity               197
Cloudiness             197
Wind Speed             197
Current Description    197
dtype: int64

In [18]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = cities_preferred_df.dropna(axis="index", how="any")
print(len(clean_df))
clean_df.head(10)

197

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Dubrovka,RU,53.6907,33.5071,15.78,96,100,4.74,snow
4,4,Elmira,US,42.0898,-76.8077,23.00,58,20,6.91,few clouds
6,6,Jamestown,US,42.0970,-79.2353,18.72,85,100,8.05,overcast clouds
7,7,Ust-Kulom,RU,53.6907,33.5071,15.78,96,100,4.74,snow
9,9,Dikson,RU,53.6907,33.5071,15.78,96,100,4.74,snow
12,12,Lavrentiya,RU,53.6907,33.5071,15.78,96,100,4.74,snow
13,13,Andenes,NO,69.3143,16.1194,28.38,93,100,11.50,overcast clouds
21,21,Belushya Guba,RU,53.6907,33.5071,15.78,96,100,4.74,snow
27,27,Tyukalinsk,RU,53.6907,33.5071,15.78,96,100,4.74,snow
28,28,Grindavik,IS,63.8424,-22.4338,30.67,86,75,3.44,broken clouds

In [19]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Dubrovka,RU,15.78,snow,53.6907,33.5071,
4,Elmira,US,23.00,few clouds,42.0898,-76.8077,
6,Jamestown,US,18.72,overcast clouds,42.0970,-79.2353,
7,Ust-Kulom,RU,15.78,snow,53.6907,33.5071,
9,Dikson,RU,15.78,snow,53.6907,33.5071,
12,Lavrentiya,RU,15.78,snow,53.6907,33.5071,
13,Andenes,NO,28.38,overcast clouds,69.3143,16.1194,
21,Belushya Guba,RU,15.78,snow,53.6907,33.5071,
27,Tyukalinsk,RU,15.78,snow,53.6907,33.5071,
28,Grindavik,IS,30.67,broken clouds,63.8424,-22.4338,

In [20]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping the city.")
        hotel_df.loc[index, "Hotel Name"] = np.nan

Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.
Hotel not found...skipping the city.

In [21]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(axis="index", how="any")
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Elmira,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"
6,Jamestown,US,18.72,overcast clouds,42.0970,-79.2353,Hampton Inn & Suites Jamestown
13,Andenes,NO,28.38,overcast clouds,69.3143,16.1194,Hotell Marena
28,Grindavik,IS,30.67,broken clouds,63.8424,-22.4338,Northern Light Inn & Max's Restaurant
32,Hilo,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"
40,Kapaa,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"
46,Fredericksburg,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"
49,Ormond Beach,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"
57,Vieques,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"
58,Fairbanks,US,23.00,few clouds,42.0898,-76.8077,"Holiday Inn Elmira - Horseheads, an IHG Hotel"

In [22]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [23]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [24]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))